"""First

Revision ID: 37f9e1aa9d04
Revises: 
Create Date: 2020-06-27 23:06:46.959435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f9e1aa9d04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_combos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('week_num', sa.Integer(), nullable=True),
    sa.Column('meal1_id', sa.Integer(), nullable=True),
    sa.Column('meal2_id', sa.Integer(), nullable=True),
    sa.Column('meal3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal1_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal2_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal3_id'], ['meals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day_of_week', 'week_num', name='user_combo_uc')
    )

    # Create a demo user
    op.execute("INSERT INTO users (username, email) VALUES ('akash', 'akash@gmail.com')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_combos')
    op.drop_table('users')
    op.drop_table('meals')
    # ### end Alembic commands ###
